/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as helloworldSol from "./helloworld.sol";
export type { helloworldSol };
import type * as salarySol from "./salary.sol";
export type { salarySol };
