/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  ITokenURIFetcher,
  ITokenURIFetcherInterface,
} from "../../../contracts/interfaces/ITokenURIFetcher";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "id",
        type: "uint256",
      },
    ],
    name: "fetchTokenURIData",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class ITokenURIFetcher__factory {
  static readonly abi = _abi;
  static createInterface(): ITokenURIFetcherInterface {
    return new utils.Interface(_abi) as ITokenURIFetcherInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ITokenURIFetcher {
    return new Contract(address, _abi, signerOrProvider) as ITokenURIFetcher;
  }
}
