/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as compoundStrategySol from "./CompoundStrategy.sol";
export type { compoundStrategySol };
import type * as sushiStrategySol from "./SushiStrategy.sol";
export type { sushiStrategySol };
