/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as moneySinkSol from "./MoneySink.sol";
export type { moneySinkSol };
export type { BentoBoxMock } from "./BentoBoxMock";
export type { DummyStrategyMock } from "./DummyStrategyMock";
export type { ERC20Mock } from "./ERC20Mock";
export type { ExternalFunctionMock } from "./ExternalFunctionMock";
export type { FlashLoanerMock } from "./FlashLoanerMock";
export type { MaliciousMasterContractMock } from "./MaliciousMasterContractMock";
export type { MasterContractMock } from "./MasterContractMock";
export type { ReturnFalseERC20Mock } from "./ReturnFalseERC20Mock";
export type { RevertingERC20Mock } from "./RevertingERC20Mock";
export type { SimpleStrategyMock } from "./SimpleStrategyMock";
export type { SneakyFlashLoanerMock } from "./SneakyFlashLoanerMock";
export type { SushiBarMock } from "./SushiBarMock";
export type { WETH9Mock } from "./WETH9Mock";
