/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as boringOwnableSol from "./BoringOwnable.sol";
export type { boringOwnableSol };
export type { Multicall } from "./Multicall";
