/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { StablePool } from "./StablePool";
export type { StablePoolFactory } from "./StablePoolFactory";
