/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IBentoBoxMinimal } from "./IBentoBoxMinimal";
export type { IERC20 } from "./IERC20";
export type { IFuroStream } from "./IFuroStream";
export type { IFuroVesting } from "./IFuroVesting";
export type { ITasker } from "./ITasker";
export type { ITokenURIFetcher } from "./ITokenURIFetcher";
