/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as compoundStrategySol from "./CompoundStrategy.sol";
export * as sushiStrategySol from "./SushiStrategy.sol";
