/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../../common";

export declare namespace ConstantProductPoolFactoryHelper {
  export type ConstantProductPoolInfoStruct = {
    tokenA: PromiseOrValue<BigNumberish>;
    tokenB: PromiseOrValue<BigNumberish>;
    reserve0: PromiseOrValue<BigNumberish>;
    reserve1: PromiseOrValue<BigNumberish>;
    swapFeeAndTwapSupport: PromiseOrValue<BigNumberish>;
  };

  export type ConstantProductPoolInfoStructOutput = [
    number,
    number,
    BigNumber,
    BigNumber,
    number
  ] & {
    tokenA: number;
    tokenB: number;
    reserve0: BigNumber;
    reserve1: BigNumber;
    swapFeeAndTwapSupport: number;
  };
}

export interface ConstantProductPoolFactoryHelperInterface
  extends utils.Interface {
  functions: {
    "getPoolsForTokens(address,address[])": FunctionFragment;
  };

  getFunction(nameOrSignatureOrTopic: "getPoolsForTokens"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getPoolsForTokens",
    values: [PromiseOrValue<string>, PromiseOrValue<string>[]]
  ): string;

  decodeFunctionResult(
    functionFragment: "getPoolsForTokens",
    data: BytesLike
  ): Result;

  events: {};
}

export interface ConstantProductPoolFactoryHelper extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ConstantProductPoolFactoryHelperInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    getPoolsForTokens(
      constantProductPoolFactory: PromiseOrValue<string>,
      tokens: PromiseOrValue<string>[],
      overrides?: CallOverrides
    ): Promise<
      [
        ConstantProductPoolFactoryHelper.ConstantProductPoolInfoStructOutput[],
        BigNumber
      ] & {
        poolInfos: ConstantProductPoolFactoryHelper.ConstantProductPoolInfoStructOutput[];
        length: BigNumber;
      }
    >;
  };

  getPoolsForTokens(
    constantProductPoolFactory: PromiseOrValue<string>,
    tokens: PromiseOrValue<string>[],
    overrides?: CallOverrides
  ): Promise<
    [
      ConstantProductPoolFactoryHelper.ConstantProductPoolInfoStructOutput[],
      BigNumber
    ] & {
      poolInfos: ConstantProductPoolFactoryHelper.ConstantProductPoolInfoStructOutput[];
      length: BigNumber;
    }
  >;

  callStatic: {
    getPoolsForTokens(
      constantProductPoolFactory: PromiseOrValue<string>,
      tokens: PromiseOrValue<string>[],
      overrides?: CallOverrides
    ): Promise<
      [
        ConstantProductPoolFactoryHelper.ConstantProductPoolInfoStructOutput[],
        BigNumber
      ] & {
        poolInfos: ConstantProductPoolFactoryHelper.ConstantProductPoolInfoStructOutput[];
        length: BigNumber;
      }
    >;
  };

  filters: {};

  estimateGas: {
    getPoolsForTokens(
      constantProductPoolFactory: PromiseOrValue<string>,
      tokens: PromiseOrValue<string>[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    getPoolsForTokens(
      constantProductPoolFactory: PromiseOrValue<string>,
      tokens: PromiseOrValue<string>[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
