/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ERC20Mock } from "./ERC20Mock";
export type { SushiSwapFactoryMock } from "./SushiSwapFactoryMock";
export type { SushiSwapPairMock } from "./SushiSwapPairMock";
export type { TaskReceiverMock } from "./TaskReceiverMock";
