/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as bentoBoxFlatSol from "./BentoBoxFlat.sol";
export type { bentoBoxFlatSol };
import type * as sushiStrategyFlatSol from "./SushiStrategyFlat.sol";
export type { sushiStrategyFlatSol };
